on:
  pull_request:
name: update
jobs:
  scrape:
    name: update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Update
      run: ./script/update.sh
